[package]
name = "axo-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI tool for Axo Framework: init, dev (hot-reload), build, and release commands"
repository.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["ui", "gui", "cli", "hot-reload", "lua"]
categories = ["gui", "command-line-utilities", "wasm"]

[dependencies]
axo-core = { path = "../core", version = "0.1" }
axo-bridge = { path = "../bridge", version = "0.1" }
axo-platforms = { path = "../platforms", version = "0.1" }
tokio.workspace = true
clap = { version = "4", features = ["derive"] }
mlua.workspace = true
