[package]
name = "lumina-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core engine for Lumina Framework: wgpu rendering, Taffy layout, text (ab_glyph), window management, permissions, device APIs"
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["ui", "gui", "wgpu", "lua", "cross-platform"]
categories = ["gui", "game-engines", "wasm"]

[dependencies]
wgpu.workspace = true
winit.workspace = true
taffy.workspace = true
tokio.workspace = true
serde.workspace = true
notify = "7"
pollster = "0.4"
bytemuck.workspace = true
dirs-next = "2.0"
ab_glyph = "0.2"
