[package]
name = "lumina-core"
version.workspace = true
edition.workspace = true

[dependencies]
wgpu.workspace = true
winit.workspace = true
taffy.workspace = true
tokio.workspace = true
serde.workspace = true
notify = "7"
pollster = "0.4"
bytemuck.workspace = true
dirs-next = "2.0"
ab_glyph = "0.2"
