[package]
name = "axo-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "JS/TS ↔ Rust bridge for Axo Framework (QuickJS)"
repository.workspace = true
homepage.workspace = true
readme = "../README.md"
keywords = ["ui", "gui", "javascript", "typescript"]
categories = ["gui", "game-engines", "wasm"]

[dependencies]
rquickjs.workspace = true
notify = "7"
serde.workspace = true
serde_json.workspace = true
taffy.workspace = true
axo-core = { path = "../core", version = "0.2" }
